#!/usr/bin/env python3
"""Regenerate src/eco_book.cpp from src/eco.pgn.

The opening book is embedded into the binary so a single executable file can
be shipped. Run this after editing src/eco.pgn, then rebuild.
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
data = (root / "src" / "eco.pgn").read_bytes()

lines = []
for i in range(0, len(data), 20):
    lines.append(", ".join(str(b) for b in data[i:i + 20]) + ",")
body = "\n    ".join(lines)

(root / "src" / "eco_book.cpp").write_text(f"""\
// Generated by scripts/embed_book.py from src/eco.pgn — do not edit by hand.
#include "eco_book.h"

const unsigned char ECO_BOOK_DATA[] = {{
    {body}
}};
const std::size_t ECO_BOOK_SIZE = sizeof(ECO_BOOK_DATA);
""")

print(f"embedded {len(data)} bytes into src/eco_book.cpp")
